# ============================================================
# MMCCCL ENTERPRISE LAB INVENTORY SYSTEM
# ============================================================

import streamlit as st
import pandas as pd
import sqlite3
from datetime import datetime
import smtplib
from email.mime.text import MIMEText
import os

# ============================================================
# CONFIGURATION
# ============================================================

DB_PATH = "lab_inventory.db"

LOW_STOCK_THRESHOLD = 2
EXPIRY_ALERT_DAYS = 30

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

EMAIL_SENDER = st.secrets["EMAIL_SENDER"]
EMAIL_PASSWORD = st.secrets["EMAIL_PASSWORD"]
EMAIL_RECEIVER = st.secrets["EMAIL_RECEIVER"]

# ============================================================
# DATABASE LAYER (ENTERPRISE)
# ============================================================

def get_conn():
    return sqlite3.connect(DB_PATH, check_same_thread=False)

    def init_db():
        conn = get_conn()
            c = conn.cursor()

                c.execute("""
                    CREATE TABLE IF NOT EXISTS inventory (
                            id INTEGER PRIMARY KEY AUTOINCREMENT,
                                    platform TEXT,
                                            type TEXT,
                                                    item TEXT,
                                                            cat_no TEXT,
                                                                    quantity INTEGER,
                                                                            expiry_date TEXT,
                                                                                    last_updated TEXT
                                                                                        )
                                                                                            """)

                                                                                                c.execute("""
                                                                                                    CREATE TABLE IF NOT EXISTS audit_log (
                                                                                                            id INTEGER PRIMARY KEY AUTOINCREMENT,
                                                                                                                    item TEXT,
                                                                                                                            action TEXT,
                                                                                                                                    quantity INTEGER,
                                                                                                                                            timestamp TEXT
                                                                                                                                                )
                                                                                                                                                    """)

                                                                                                                                                        c.execute("""
                                                                                                                                                            CREATE TABLE IF NOT EXISTS system_log (
                                                                                                                                                                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                                                                                                                                                                            last_alert_sent TEXT
                                                                                                                                                                                )
                                                                                                                                                                                    """)

                                                                                                                                                                                        conn.commit()
                                                                                                                                                                                            conn.close()

                                                                                                                                                                                            init_db()

                                                                                                                                                                                            # ============================================================
                                                                                                                                                                                            # EMAIL ENGINE
                                                                                                                                                                                            # ============================================================

                                                                                                                                                                                            def send_email(subject, body):

                                                                                                                                                                                                try:
                                                                                                                                                                                                        msg = MIMEText(body)
                                                                                                                                                                                                                msg["Subject"] = subject
                                                                                                                                                                                                                        msg["From"] = EMAIL_SENDER
                                                                                                                                                                                                                                msg["To"] = EMAIL_RECEIVER

                                                                                                                                                                                                                                        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
                                                                                                                                                                                                                                                    server.starttls()
                                                                                                                                                                                                                                                                server.login(EMAIL_SENDER, EMAIL_PASSWORD)
                                                                                                                                                                                                                                                                            server.send_message(msg)

                                                                                                                                                                                                                                                                                    return True

                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                st.error(f"Email error: {e}")
                                                                                                                                                                                                                                                                                                        return False

                                                                                                                                                                                                                                                                                                        # ============================================================
                                                                                                                                                                                                                                                                                                        # DATA ACCESS
                                                                                                                                                                                                                                                                                                        # ============================================================

                                                                                                                                                                                                                                                                                                        def load_data():
                                                                                                                                                                                                                                                                                                            conn = get_conn()
                                                                                                                                                                                                                                                                                                                df = pd.read_sql("SELECT * FROM inventory", conn)
                                                                                                                                                                                                                                                                                                                    conn.close()
                                                                                                                                                                                                                                                                                                                        return df

                                                                                                                                                                                                                                                                                                                        def save_to_db(df):
                                                                                                                                                                                                                                                                                                                            conn = get_conn()
                                                                                                                                                                                                                                                                                                                                df.to_sql("inventory", conn, if_exists="replace", index=False)
                                                                                                                                                                                                                                                                                                                                    conn.close()

                                                                                                                                                                                                                                                                                                                                    def log_action(item, action, qty):
                                                                                                                                                                                                                                                                                                                                        conn = get_conn()
                                                                                                                                                                                                                                                                                                                                            c = conn.cursor()
                                                                                                                                                                                                                                                                                                                                                c.execute("""
                                                                                                                                                                                                                                                                                                                                                        INSERT INTO audit_log (item, action, quantity, timestamp)
                                                                                                                                                                                                                                                                                                                                                                VALUES (?, ?, ?, ?)
                                                                                                                                                                                                                                                                                                                                                                    """, (item, action, qty, datetime.now()))
                                                                                                                                                                                                                                                                                                                                                                        conn.commit()
                                                                                                                                                                                                                                                                                                                                                                            conn.close()

                                                                                                                                                                                                                                                                                                                                                                            # ============================================================
                                                                                                                                                                                                                                                                                                                                                                            # STATUS ENGINE
                                                                                                                                                                                                                                                                                                                                                                            # ============================================================

                                                                                                                                                                                                                                                                                                                                                                            def compute_status(df):

                                                                                                                                                                                                                                                                                                                                                                                today = pd.to_datetime(datetime.now().date())

                                                                                                                                                                                                                                                                                                                                                                                    df["expiry_date"] = pd.to_datetime(df["expiry_date"], errors="coerce")

                                                                                                                                                                                                                                                                                                                                                                                        df["status"] = "ok"

                                                                                                                                                                                                                                                                                                                                                                                            df.loc[df["expiry_date"] < today, "status"] = "expired"

                                                                                                                                                                                                                                                                                                                                                                                                df.loc[
                                                                                                                                                                                                                                                                                                                                                                                                        (df["expiry_date"] >= today) &
                                                                                                                                                                                                                                                                                                                                                                                                                (df["expiry_date"] <= today + pd.Timedelta(days=EXPIRY_ALERT_DAYS)),
                                                                                                                                                                                                                                                                                                                                                                                                                        "status"
                                                                                                                                                                                                                                                                                                                                                                                                                            ] = "expiring_soon"

                                                                                                                                                                                                                                                                                                                                                                                                                                df.loc[df["quantity"] <= LOW_STOCK_THRESHOLD, "low_stock"] = True

                                                                                                                                                                                                                                                                                                                                                                                                                                    return df

                                                                                                                                                                                                                                                                                                                                                                                                                                    # ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                    # ALERT ENGINE
                                                                                                                                                                                                                                                                                                                                                                                                                                    # ============================================================

                                                                                                                                                                                                                                                                                                                                                                                                                                    def generate_alerts(df):

                                                                                                                                                                                                                                                                                                                                                                                                                                        low_stock = df[df["quantity"] <= LOW_STOCK_THRESHOLD]
                                                                                                                                                                                                                                                                                                                                                                                                                                            expiring = df[df["status"] == "expiring_soon"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                expired = df[df["status"] == "expired"]

                                                                                                                                                                                                                                                                                                                                                                                                                                                    return low_stock, expiring, expired


                                                                                                                                                                                                                                                                                                                                                                                                                                                    def send_daily_alert(df):

                                                                                                                                                                                                                                                                                                                                                                                                                                                        conn = get_conn()
                                                                                                                                                                                                                                                                                                                                                                                                                                                            log = pd.read_sql("SELECT * FROM system_log", conn)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                now = datetime.now()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not log.empty:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            last = pd.to_datetime(log.iloc[0]["last_alert_sent"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (now - last).days < 1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    low, expiring, expired = generate_alerts(df)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if len(low) == 0 and len(expired) == 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    body = f"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        LAB ALERT REPORT

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            LOW STOCK:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {low[['item','quantity']].to_string(index=False)}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EXPIRING:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {expiring[['item','expiry_date']].to_string(index=False)}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EXPIRED:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {expired[['item','expiry_date']].to_string(index=False)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        send_email("🚨 DAILY LAB ALERT", body)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            conn.execute("DELETE FROM system_log")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                conn.execute("INSERT INTO system_log (last_alert_sent) VALUES (?)", (now,))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    conn.commit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        conn.close()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # UI START
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # ============================================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.set_page_config(layout="wide")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.title("🧪 MMCCCL Enterprise Lab Inventory System")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        df = load_data()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if df.empty:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.warning("No data found. Upload initial Excel.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                uploaded = st.file_uploader("Upload Excel", type=["xlsx"])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if uploaded:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            df = pd.read_excel(uploaded)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    df["last_updated"] = datetime.now()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            save_to_db(df)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.success("Data loaded to database")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.rerun()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.stop()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # PROCESS DATA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ============================================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                df = compute_status(df)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                low, expiring, expired = generate_alerts(df)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # AUTO ALERT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                send_daily_alert(df)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # EXECUTIVE DASHBOARD
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ============================================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.header("📊 Executive Dashboard")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                total_items = len(df)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                total_qty = df["quantity"].sum()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                expired_count = len(expired)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                low_stock_count = len(low)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                health_score = max(0, 100 - expired_count*10 - low_stock_count*5)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                col1, col2, col3, col4, col5 = st.columns(5)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                col1.metric("Total Items", total_items)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                col2.metric("Total Quantity", int(total_qty))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                col3.metric("Expired", expired_count)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                col4.metric("Low Stock", low_stock_count)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                col5.metric("Health Score", f"{health_score}/100")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.markdown("---")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ALERT PANEL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ============================================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.header("🚨 Alerts")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with st.expander("Low Stock"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.dataframe(low)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    with st.expander("Expiring Soon"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.dataframe(expiring)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with st.expander("Expired"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.dataframe(expired)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if st.button("Send Alert Email"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                send_daily_alert(df)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.success("Alert sent")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # INVENTORY EDITOR
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # ============================================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.header("Inventory Management")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    edited = st.data_editor(df, num_rows="dynamic")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if st.button("Save Changes"):

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        edited["last_updated"] = datetime.now()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            save_to_db(edited)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.success("Saved to database")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.rerun()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # COLOR CODING
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # ============================================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def highlight(row):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if row["status"] == "expired":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return ["background-color: red"]*len(row)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif row["status"] == "expiring_soon":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return ["background-color: orange"]*len(row)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif row["quantity"] <= LOW_STOCK_THRESHOLD:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return ["background-color: yellow"]*len(row)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return [""]*len(row)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.dataframe(df.style.apply(highlight, axis=1))